### PR TITLE
Add support for Alias

### PR DESCRIPTION
**Pull request by samuelreh**

### CODE REVIEW

**Comment by f2prateek** [comment]
LGTM! cc @sperand-io

**Comment by samuelreh** [comment]
@f2prateek any updates on this?

**Comment by anark** [comment]
@f2prateek @sperand-io @yields  Any way to get this merged in or get an update on what it needs?  Our customers want to use alias with segment and this is all thats stopping them

**Comment by sperand-io** [comment]
thanks @samuelreh @anark apologies for the delay!

**Comment by sperand-io** [comment]
(deployed :) )

**Comment by samuelreh** [comment]
Woohoo! Thanks @sperand-io !

**Pull request merged**
